### ISSUE TITLE
Nombre

### ISSUE THREAD

**Issue by raulghm** [YerkoPalma/npm-chile#2]
Solo por trending podria llamarse `awesome-npm-chile` o parecido IMHO.

Buen pega ;)

**Comment by YerkoPalma** [comment]
Hola :wave: 
Interesante sugerencia, aunque para tener una lista awesome, hay que cumplir una serie de requisitos, y por ahora no creo que los cumpla. Además, esta lista sigue siendo más pequeña de lo que me gustaria :disappointed: 
Si llega a crecer lo suficiente, consideraria convertirla en una lista awesome, mientras tanto, me parece que esta bien así.

Saludos.
